






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace MS.Sc.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IVideo_Slide Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Home/Video Slide</para>	
	/// <para>ID: 10fa6de3-e011-48ce-ab1f-7e792ed7008c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IVideo_SlideConstants.TemplateIdString )] //, Cachable = true
	public partial interface IVideo_Slide : IGlassBase , global::MS.Sc.Models.IItem_Base
	{
			
					/// <summary>
					/// The Arrow Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: aaaa4391-e377-4cf9-8dfc-467b834c1494</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IVideo_SlideConstants.Arrow_ImageFieldName)]
					Image Arrow_Image  {get; set;}
			
			
					/// <summary>
					/// The Background Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: ca894ddf-ec5c-4bc2-a8b9-99be7776dbbd</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IVideo_SlideConstants.Background_ImageFieldName)]
					Image Background_Image  {get; set;}
			
			
					/// <summary>
					/// The Video field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: ce0c2818-148e-4a75-b0ee-6d3371f5a9f7</para>
					/// <para>Custom Data: type=MS_Video</para>
					/// </summary>
					[SitecoreField(IVideo_SlideConstants.VideoFieldName)]
					MS_Video Video  {get; set;}
			
			
	}


	public static partial class IVideo_SlideConstants{

			public const string TemplateIdString = "10fa6de3-e011-48ce-ab1f-7e792ed7008c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Video Slide";

		
			
			public static readonly ID Arrow_ImageFieldId = new ID("aaaa4391-e377-4cf9-8dfc-467b834c1494");
			public const string Arrow_ImageFieldName = "Arrow Image";
			
		
			
			public static readonly ID Background_ImageFieldId = new ID("ca894ddf-ec5c-4bc2-a8b9-99be7776dbbd");
			public const string Background_ImageFieldName = "Background Image";
			
		
			
			public static readonly ID VideoFieldId = new ID("ce0c2818-148e-4a75-b0ee-6d3371f5a9f7");
			public const string VideoFieldName = "Video";
			
		
			
			public static readonly ID DescriptionFieldId = new ID("c6cda4a3-5d5b-445a-a33e-003bac3fe9d5");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("db7fef5a-0957-4fe3-abe6-e33bb46fc8c4");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Video_Slide
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Home/Video Slide</para>	
	/// <para>ID: 10fa6de3-e011-48ce-ab1f-7e792ed7008c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IVideo_SlideConstants.TemplateIdString)] //, Cachable = true
	public partial class Video_Slide  : GlassBase, IVideo_Slide 
	{
	   
		
				/// <summary>
				/// The Arrow Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: aaaa4391-e377-4cf9-8dfc-467b834c1494</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IVideo_SlideConstants.Arrow_ImageFieldName)]
				public virtual Image Arrow_Image  {get; set;}
					
		
				/// <summary>
				/// The Background Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: ca894ddf-ec5c-4bc2-a8b9-99be7776dbbd</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IVideo_SlideConstants.Background_ImageFieldName)]
				public virtual Image Background_Image  {get; set;}
					
		
				/// <summary>
				/// The Video field.
				/// <para></para>
				/// <para>Field Type: Droplink</para>		
				/// <para>Field ID: ce0c2818-148e-4a75-b0ee-6d3371f5a9f7</para>
				/// <para>Custom Data: type=MS_Video</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IVideo_SlideConstants.VideoFieldName)]
				public virtual MS_Video Video  {get; set;}
					
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c6cda4a3-5d5b-445a-a33e-003bac3fe9d5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IVideo_SlideConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: db7fef5a-0957-4fe3-abe6-e33bb46fc8c4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IVideo_SlideConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IPage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Base/Page</para>	
	/// <para>ID: 406cdf1f-63a9-40b1-839c-196695a966d1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPage : IGlassBase , global::MS.Sc.Models.IItem_Base, global::MS.Sc.Models.IMetadata
	{
			
					/// <summary>
					/// The CSS Classes field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: cdd223e1-4c95-47fb-a7a6-9670693cb243</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageConstants.CSS_ClassesFieldName)]
					string CSS_Classes  {get; set;}
			
			
					/// <summary>
					/// The Background Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: b24c74da-fccc-40c8-ae9e-d42fba7b4620</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageConstants.Background_ImageFieldName)]
					Image Background_Image  {get; set;}
			
			
	}


	public static partial class IPageConstants{

			public const string TemplateIdString = "406cdf1f-63a9-40b1-839c-196695a966d1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page";

		
			
			public static readonly ID CSS_ClassesFieldId = new ID("cdd223e1-4c95-47fb-a7a6-9670693cb243");
			public const string CSS_ClassesFieldName = "CSS Classes";
			
		
			
			public static readonly ID Background_ImageFieldId = new ID("b24c74da-fccc-40c8-ae9e-d42fba7b4620");
			public const string Background_ImageFieldName = "Background Image";
			
		
			
			public static readonly ID DescriptionFieldId = new ID("c6cda4a3-5d5b-445a-a33e-003bac3fe9d5");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("db7fef5a-0957-4fe3-abe6-e33bb46fc8c4");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("b4ea1307-f39a-470f-84bb-ca7269fdb392");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("f1cd55be-14d3-4958-8e30-cc9789877818");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("ed6e4953-c3ef-4f60-b022-f6b024e54660");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Base/Page</para>	
	/// <para>ID: 406cdf1f-63a9-40b1-839c-196695a966d1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageConstants.TemplateIdString)] //, Cachable = true
	public partial class Page  : GlassBase, IPage 
	{
	   
		
				/// <summary>
				/// The CSS Classes field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: cdd223e1-4c95-47fb-a7a6-9670693cb243</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.CSS_ClassesFieldName)]
				public virtual string CSS_Classes  {get; set;}
					
		
				/// <summary>
				/// The Background Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: b24c74da-fccc-40c8-ae9e-d42fba7b4620</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.Background_ImageFieldName)]
				public virtual Image Background_Image  {get; set;}
					
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c6cda4a3-5d5b-445a-a33e-003bac3fe9d5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: db7fef5a-0957-4fe3-abe6-e33bb46fc8c4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b4ea1307-f39a-470f-84bb-ca7269fdb392</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f1cd55be-14d3-4958-8e30-cc9789877818</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ed6e4953-c3ef-4f60-b022-f6b024e54660</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IHeader Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Shared/Header</para>	
	/// <para>ID: 4754ac46-0478-4958-b485-99329ae5f139</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHeaderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHeader : IGlassBase 
	{
			
					/// <summary>
					/// The Menu Items field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: bb1cbe07-0559-42b0-a44e-cd5bccb8ae65</para>
					/// <para>Custom Data: generic=Page</para>
					/// </summary>
					[SitecoreField(IHeaderConstants.Menu_ItemsFieldName)]
					IEnumerable<Page> Menu_Items  {get; set;}
			
			
					/// <summary>
					/// The Social Networks field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: f78ba614-364e-449d-b8ef-bd1aa6f261e9</para>
					/// <para>Custom Data: generic=Social_Network</para>
					/// </summary>
					[SitecoreField(IHeaderConstants.Social_NetworksFieldName)]
					IEnumerable<Social_Network> Social_Networks  {get; set;}
			
			
					/// <summary>
					/// The Link Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 63be7af6-2aa4-46eb-be94-c8fb625a97c8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeaderConstants.Link_TitleFieldName)]
					string Link_Title  {get; set;}
			
			
					/// <summary>
					/// The Link field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: d82cc7f9-d223-4841-b73e-689422ab125d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeaderConstants.LinkFieldName)]
					Link Link  {get; set;}
			
			
					/// <summary>
					/// The Logo field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 88d1014d-febd-4a91-af80-204f7cf7e301</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeaderConstants.LogoFieldName)]
					Image Logo  {get; set;}
			
			
	}


	public static partial class IHeaderConstants{

			public const string TemplateIdString = "4754ac46-0478-4958-b485-99329ae5f139";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Header";

		
			
			public static readonly ID Menu_ItemsFieldId = new ID("bb1cbe07-0559-42b0-a44e-cd5bccb8ae65");
			public const string Menu_ItemsFieldName = "Menu Items";
			
		
			
			public static readonly ID Social_NetworksFieldId = new ID("f78ba614-364e-449d-b8ef-bd1aa6f261e9");
			public const string Social_NetworksFieldName = "Social Networks";
			
		
			
			public static readonly ID Link_TitleFieldId = new ID("63be7af6-2aa4-46eb-be94-c8fb625a97c8");
			public const string Link_TitleFieldName = "Link Title";
			
		
			
			public static readonly ID LinkFieldId = new ID("d82cc7f9-d223-4841-b73e-689422ab125d");
			public const string LinkFieldName = "Link";
			
		
			
			public static readonly ID LogoFieldId = new ID("88d1014d-febd-4a91-af80-204f7cf7e301");
			public const string LogoFieldName = "Logo";
			
			

	}

	
	/// <summary>
	/// Header
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Shared/Header</para>	
	/// <para>ID: 4754ac46-0478-4958-b485-99329ae5f139</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHeaderConstants.TemplateIdString)] //, Cachable = true
	public partial class Header  : GlassBase, IHeader 
	{
	   
		
				/// <summary>
				/// The Menu Items field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: bb1cbe07-0559-42b0-a44e-cd5bccb8ae65</para>
				/// <para>Custom Data: generic=Page</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.Menu_ItemsFieldName)]
				public virtual IEnumerable<Page> Menu_Items  {get; set;}
					
		
				/// <summary>
				/// The Social Networks field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: f78ba614-364e-449d-b8ef-bd1aa6f261e9</para>
				/// <para>Custom Data: generic=Social_Network</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.Social_NetworksFieldName)]
				public virtual IEnumerable<Social_Network> Social_Networks  {get; set;}
					
		
				/// <summary>
				/// The Link Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 63be7af6-2aa4-46eb-be94-c8fb625a97c8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.Link_TitleFieldName)]
				public virtual string Link_Title  {get; set;}
					
		
				/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: d82cc7f9-d223-4841-b73e-689422ab125d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.LinkFieldName)]
				public virtual Link Link  {get; set;}
					
		
				/// <summary>
				/// The Logo field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 88d1014d-febd-4a91-af80-204f7cf7e301</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.LogoFieldName)]
				public virtual Image Logo  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IMS_Video Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Media/MS Video</para>	
	/// <para>ID: 4e508908-bcd7-4ef0-98a9-568bdb1fc30d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMS_VideoConstants.TemplateIdString )] //, Cachable = true
	public partial interface IMS_Video : IGlassBase 
	{
			
					/// <summary>
					/// The MP4 Video field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: 347e4e85-3962-4326-ba48-e7da4eec3bc1</para>
					/// <para>Custom Data: type=VideoFile</para>
					/// </summary>
					[SitecoreField(IMS_VideoConstants.MP4_VideoFieldName)]
					VideoFile MP4_Video  {get; set;}
			
			
					/// <summary>
					/// The Name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 565f0e2c-0cd9-48fc-ab77-38643731463a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMS_VideoConstants.NameFieldName)]
					string Name  {get; set;}
			
			
					/// <summary>
					/// The OGG Video field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: 6c036c23-4359-468f-82cd-3679f4d7ca82</para>
					/// <para>Custom Data: type=File</para>
					/// </summary>
					[SitecoreField(IMS_VideoConstants.OGG_VideoFieldName)]
					File OGG_Video  {get; set;}
			
			
					/// <summary>
					/// The WebM Video field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: dd9373c4-44e3-4398-9e15-cc0a16e5b9b2</para>
					/// <para>Custom Data: type=File</para>
					/// </summary>
					[SitecoreField(IMS_VideoConstants.WebM_VideoFieldName)]
					File WebM_Video  {get; set;}
			
			
	}


	public static partial class IMS_VideoConstants{

			public const string TemplateIdString = "4e508908-bcd7-4ef0-98a9-568bdb1fc30d";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "MS Video";

		
			
			public static readonly ID MP4_VideoFieldId = new ID("347e4e85-3962-4326-ba48-e7da4eec3bc1");
			public const string MP4_VideoFieldName = "MP4 Video";
			
		
			
			public static readonly ID NameFieldId = new ID("565f0e2c-0cd9-48fc-ab77-38643731463a");
			public const string NameFieldName = "Name";
			
		
			
			public static readonly ID OGG_VideoFieldId = new ID("6c036c23-4359-468f-82cd-3679f4d7ca82");
			public const string OGG_VideoFieldName = "OGG Video";
			
		
			
			public static readonly ID WebM_VideoFieldId = new ID("dd9373c4-44e3-4398-9e15-cc0a16e5b9b2");
			public const string WebM_VideoFieldName = "WebM Video";
			
			

	}

	
	/// <summary>
	/// MS_Video
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Media/MS Video</para>	
	/// <para>ID: 4e508908-bcd7-4ef0-98a9-568bdb1fc30d</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMS_VideoConstants.TemplateIdString)] //, Cachable = true
	public partial class MS_Video  : GlassBase, IMS_Video 
	{
	   
		
				/// <summary>
				/// The MP4 Video field.
				/// <para></para>
				/// <para>Field Type: Droptree</para>		
				/// <para>Field ID: 347e4e85-3962-4326-ba48-e7da4eec3bc1</para>
				/// <para>Custom Data: type=VideoFile</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMS_VideoConstants.MP4_VideoFieldName)]
				public virtual VideoFile MP4_Video  {get; set;}
					
		
				/// <summary>
				/// The Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 565f0e2c-0cd9-48fc-ab77-38643731463a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMS_VideoConstants.NameFieldName)]
				public virtual string Name  {get; set;}
					
		
				/// <summary>
				/// The OGG Video field.
				/// <para></para>
				/// <para>Field Type: Droptree</para>		
				/// <para>Field ID: 6c036c23-4359-468f-82cd-3679f4d7ca82</para>
				/// <para>Custom Data: type=File</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMS_VideoConstants.OGG_VideoFieldName)]
				public virtual File OGG_Video  {get; set;}
					
		
				/// <summary>
				/// The WebM Video field.
				/// <para></para>
				/// <para>Field Type: Droptree</para>		
				/// <para>Field ID: dd9373c4-44e3-4398-9e15-cc0a16e5b9b2</para>
				/// <para>Custom Data: type=File</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMS_VideoConstants.WebM_VideoFieldName)]
				public virtual File WebM_Video  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// ISite Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Site</para>	
	/// <para>ID: 70e5cab5-fd8d-4073-be6b-cd2e1bf76fc7</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISite : IGlassBase 
	{
			
					/// <summary>
					/// The AnalyticsAccountCode field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: d226c608-b04c-4a78-b5ac-085a2194d0ed</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteConstants.AnalyticsAccountCodeFieldName)]
					string AnalyticsAccountCode  {get; set;}
			
			
	}


	public static partial class ISiteConstants{

			public const string TemplateIdString = "70e5cab5-fd8d-4073-be6b-cd2e1bf76fc7";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site";

		
			
			public static readonly ID AnalyticsAccountCodeFieldId = new ID("d226c608-b04c-4a78-b5ac-085a2194d0ed");
			public const string AnalyticsAccountCodeFieldName = "AnalyticsAccountCode";
			
			

	}

	
	/// <summary>
	/// Site
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Site</para>	
	/// <para>ID: 70e5cab5-fd8d-4073-be6b-cd2e1bf76fc7</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString)] //, Cachable = true
	public partial class Site  : GlassBase, ISite 
	{
	   
		
				/// <summary>
				/// The AnalyticsAccountCode field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d226c608-b04c-4a78-b5ac-085a2194d0ed</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteConstants.AnalyticsAccountCodeFieldName)]
				public virtual string AnalyticsAccountCode  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// ICase_Study_Slide Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Home/Case Study Slide</para>	
	/// <para>ID: 96a2265c-f974-48e2-9a5d-f22028f14ef6</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICase_Study_SlideConstants.TemplateIdString )] //, Cachable = true
	public partial interface ICase_Study_Slide : IGlassBase , global::MS.Sc.Models.IItem_Base
	{
			
					/// <summary>
					/// The Author field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a0aef149-9716-44ab-acc8-d26c32bf3a88</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICase_Study_SlideConstants.AuthorFieldName)]
					string Author  {get; set;}
			
			
					/// <summary>
					/// The Background Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 0878843e-0e3b-48ae-acbb-86f313341650</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICase_Study_SlideConstants.Background_ImageFieldName)]
					Image Background_Image  {get; set;}
			
			
					/// <summary>
					/// The Company Name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 78e36448-9cd0-4c10-b56d-6eb7d5ce01b3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICase_Study_SlideConstants.Company_NameFieldName)]
					string Company_Name  {get; set;}
			
			
					/// <summary>
					/// The CSS Class field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 05936364-450f-41e0-8fdb-e32e531f5f5b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICase_Study_SlideConstants.CSS_ClassFieldName)]
					string CSS_Class  {get; set;}
			
			
					/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: c80c7dd4-9cfd-4001-ae8a-b23226932aed</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICase_Study_SlideConstants.ImageFieldName)]
					Image Image  {get; set;}
			
			
					/// <summary>
					/// The Video field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: 052c2096-0374-4b92-b64c-0a565d6cd35e</para>
					/// <para>Custom Data: type=MS_Video</para>
					/// </summary>
					[SitecoreField(ICase_Study_SlideConstants.VideoFieldName)]
					MS_Video Video  {get; set;}
			
			
	}


	public static partial class ICase_Study_SlideConstants{

			public const string TemplateIdString = "96a2265c-f974-48e2-9a5d-f22028f14ef6";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Case Study Slide";

		
			
			public static readonly ID AuthorFieldId = new ID("a0aef149-9716-44ab-acc8-d26c32bf3a88");
			public const string AuthorFieldName = "Author";
			
		
			
			public static readonly ID Background_ImageFieldId = new ID("0878843e-0e3b-48ae-acbb-86f313341650");
			public const string Background_ImageFieldName = "Background Image";
			
		
			
			public static readonly ID Company_NameFieldId = new ID("78e36448-9cd0-4c10-b56d-6eb7d5ce01b3");
			public const string Company_NameFieldName = "Company Name";
			
		
			
			public static readonly ID CSS_ClassFieldId = new ID("05936364-450f-41e0-8fdb-e32e531f5f5b");
			public const string CSS_ClassFieldName = "CSS Class";
			
		
			
			public static readonly ID ImageFieldId = new ID("c80c7dd4-9cfd-4001-ae8a-b23226932aed");
			public const string ImageFieldName = "Image";
			
		
			
			public static readonly ID VideoFieldId = new ID("052c2096-0374-4b92-b64c-0a565d6cd35e");
			public const string VideoFieldName = "Video";
			
		
			
			public static readonly ID DescriptionFieldId = new ID("c6cda4a3-5d5b-445a-a33e-003bac3fe9d5");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("db7fef5a-0957-4fe3-abe6-e33bb46fc8c4");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Case_Study_Slide
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Home/Case Study Slide</para>	
	/// <para>ID: 96a2265c-f974-48e2-9a5d-f22028f14ef6</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICase_Study_SlideConstants.TemplateIdString)] //, Cachable = true
	public partial class Case_Study_Slide  : GlassBase, ICase_Study_Slide 
	{
	   
		
				/// <summary>
				/// The Author field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a0aef149-9716-44ab-acc8-d26c32bf3a88</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICase_Study_SlideConstants.AuthorFieldName)]
				public virtual string Author  {get; set;}
					
		
				/// <summary>
				/// The Background Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 0878843e-0e3b-48ae-acbb-86f313341650</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICase_Study_SlideConstants.Background_ImageFieldName)]
				public virtual Image Background_Image  {get; set;}
					
		
				/// <summary>
				/// The Company Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 78e36448-9cd0-4c10-b56d-6eb7d5ce01b3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICase_Study_SlideConstants.Company_NameFieldName)]
				public virtual string Company_Name  {get; set;}
					
		
				/// <summary>
				/// The CSS Class field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 05936364-450f-41e0-8fdb-e32e531f5f5b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICase_Study_SlideConstants.CSS_ClassFieldName)]
				public virtual string CSS_Class  {get; set;}
					
		
				/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c80c7dd4-9cfd-4001-ae8a-b23226932aed</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICase_Study_SlideConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
		
				/// <summary>
				/// The Video field.
				/// <para></para>
				/// <para>Field Type: Droptree</para>		
				/// <para>Field ID: 052c2096-0374-4b92-b64c-0a565d6cd35e</para>
				/// <para>Custom Data: type=MS_Video</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICase_Study_SlideConstants.VideoFieldName)]
				public virtual MS_Video Video  {get; set;}
					
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c6cda4a3-5d5b-445a-a33e-003bac3fe9d5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICase_Study_SlideConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: db7fef5a-0957-4fe3-abe6-e33bb46fc8c4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICase_Study_SlideConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IPage_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Base/Page Content</para>	
	/// <para>ID: ae8a0bc1-a3e9-4237-a4c2-b49789f07bce</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_ContentConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPage_Content : IGlassBase 
	{
			
	}


	public static partial class IPage_ContentConstants{

			public const string TemplateIdString = "ae8a0bc1-a3e9-4237-a4c2-b49789f07bce";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page Content";

			

	}

	
	/// <summary>
	/// Page_Content
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Base/Page Content</para>	
	/// <para>ID: ae8a0bc1-a3e9-4237-a4c2-b49789f07bce</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPage_ContentConstants.TemplateIdString)] //, Cachable = true
	public partial class Page_Content  : GlassBase, IPage_Content 
	{
	   
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// ICase_Studies_Slider Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Home/Case Studies Slider</para>	
	/// <para>ID: b7e6d488-0ac8-420e-974c-c5cfc22e9882</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICase_Studies_SliderConstants.TemplateIdString )] //, Cachable = true
	public partial interface ICase_Studies_Slider : IGlassBase , global::MS.Sc.Models.IItem_Base
	{
			
					/// <summary>
					/// The Slides field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: b23bf9a0-8a9e-4dbb-a7d1-551cf2008d52</para>
					/// <para>Custom Data: generic=Case_Study_Slide</para>
					/// </summary>
					[SitecoreField(ICase_Studies_SliderConstants.SlidesFieldName)]
					IEnumerable<Case_Study_Slide> Slides  {get; set;}
			
			
	}


	public static partial class ICase_Studies_SliderConstants{

			public const string TemplateIdString = "b7e6d488-0ac8-420e-974c-c5cfc22e9882";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Case Studies Slider";

		
			
			public static readonly ID SlidesFieldId = new ID("b23bf9a0-8a9e-4dbb-a7d1-551cf2008d52");
			public const string SlidesFieldName = "Slides";
			
		
			
			public static readonly ID DescriptionFieldId = new ID("c6cda4a3-5d5b-445a-a33e-003bac3fe9d5");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("db7fef5a-0957-4fe3-abe6-e33bb46fc8c4");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Case_Studies_Slider
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Home/Case Studies Slider</para>	
	/// <para>ID: b7e6d488-0ac8-420e-974c-c5cfc22e9882</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICase_Studies_SliderConstants.TemplateIdString)] //, Cachable = true
	public partial class Case_Studies_Slider  : GlassBase, ICase_Studies_Slider 
	{
	   
		
				/// <summary>
				/// The Slides field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: b23bf9a0-8a9e-4dbb-a7d1-551cf2008d52</para>
				/// <para>Custom Data: generic=Case_Study_Slide</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICase_Studies_SliderConstants.SlidesFieldName)]
				public virtual IEnumerable<Case_Study_Slide> Slides  {get; set;}
					
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c6cda4a3-5d5b-445a-a33e-003bac3fe9d5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICase_Studies_SliderConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: db7fef5a-0957-4fe3-abe6-e33bb46fc8c4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICase_Studies_SliderConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IMetadata Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Base/Metadata</para>	
	/// <para>ID: d476c1c3-20c1-4739-af76-2dec8c7c5c43</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMetadataConstants.TemplateIdString )] //, Cachable = true
	public partial interface IMetadata : IGlassBase 
	{
			
					/// <summary>
					/// The Meta Description field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b4ea1307-f39a-470f-84bb-ca7269fdb392</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMetadataConstants.Meta_DescriptionFieldName)]
					string Meta_Description  {get; set;}
			
			
					/// <summary>
					/// The Meta Keywords field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f1cd55be-14d3-4958-8e30-cc9789877818</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMetadataConstants.Meta_KeywordsFieldName)]
					string Meta_Keywords  {get; set;}
			
			
					/// <summary>
					/// The Meta Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ed6e4953-c3ef-4f60-b022-f6b024e54660</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMetadataConstants.Meta_TitleFieldName)]
					string Meta_Title  {get; set;}
			
			
	}


	public static partial class IMetadataConstants{

			public const string TemplateIdString = "d476c1c3-20c1-4739-af76-2dec8c7c5c43";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Metadata";

		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("b4ea1307-f39a-470f-84bb-ca7269fdb392");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("f1cd55be-14d3-4958-8e30-cc9789877818");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("ed6e4953-c3ef-4f60-b022-f6b024e54660");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Metadata
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Base/Metadata</para>	
	/// <para>ID: d476c1c3-20c1-4739-af76-2dec8c7c5c43</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMetadataConstants.TemplateIdString)] //, Cachable = true
	public partial class Metadata  : GlassBase, IMetadata 
	{
	   
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b4ea1307-f39a-470f-84bb-ca7269fdb392</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMetadataConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f1cd55be-14d3-4958-8e30-cc9789877818</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMetadataConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ed6e4953-c3ef-4f60-b022-f6b024e54660</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMetadataConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IVideoFile Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Media/VideoFile</para>	
	/// <para>ID: d834a533-bda3-4c3e-aa8f-6efcb7ddc316</para>	
	/// </summary>
	[SitecoreType(TemplateId=IVideoFileConstants.TemplateIdString )] //, Cachable = true
	public partial interface IVideoFile : IGlassBase 
	{
			
	}


	public static partial class IVideoFileConstants{

			public const string TemplateIdString = "d834a533-bda3-4c3e-aa8f-6efcb7ddc316";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "VideoFile";

			

	}

	
	/// <summary>
	/// VideoFile
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Media/VideoFile</para>	
	/// <para>ID: d834a533-bda3-4c3e-aa8f-6efcb7ddc316</para>	
	/// </summary>
	[SitecoreType(TemplateId=IVideoFileConstants.TemplateIdString)] //, Cachable = true
	public partial class VideoFile  : GlassBase, IVideoFile 
	{
	   
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IFile Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Media/File</para>	
	/// <para>ID: d98e4461-2740-4ccd-b5e8-50df298a08c0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFileConstants.TemplateIdString )] //, Cachable = true
	public partial interface IFile : IGlassBase 
	{
			
	}


	public static partial class IFileConstants{

			public const string TemplateIdString = "d98e4461-2740-4ccd-b5e8-50df298a08c0";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "File";

			

	}

	
	/// <summary>
	/// File
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Media/File</para>	
	/// <para>ID: d98e4461-2740-4ccd-b5e8-50df298a08c0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFileConstants.TemplateIdString)] //, Cachable = true
	public partial class File  : GlassBase, IFile 
	{
	   
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// ISocial_Network Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Shared/Social Network</para>	
	/// <para>ID: e06a4f0b-6d79-423b-9c6f-5c54e6c62a9b</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISocial_NetworkConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISocial_Network : IGlassBase 
	{
			
					/// <summary>
					/// The CSS Class field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 9ce4dc51-afa1-413d-a97f-70ec4c58c94f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISocial_NetworkConstants.CSS_ClassFieldName)]
					string CSS_Class  {get; set;}
			
			
					/// <summary>
					/// The Link field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: e0b7ceaa-3cbd-48f0-99f9-350c501eb3b9</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISocial_NetworkConstants.LinkFieldName)]
					Link Link  {get; set;}
			
			
					/// <summary>
					/// The Name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 1fe8a8a2-87f2-49c2-80bb-108ef19ece16</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISocial_NetworkConstants.NameFieldName)]
					string Name  {get; set;}
			
			
	}


	public static partial class ISocial_NetworkConstants{

			public const string TemplateIdString = "e06a4f0b-6d79-423b-9c6f-5c54e6c62a9b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Social Network";

		
			
			public static readonly ID CSS_ClassFieldId = new ID("9ce4dc51-afa1-413d-a97f-70ec4c58c94f");
			public const string CSS_ClassFieldName = "CSS Class";
			
		
			
			public static readonly ID LinkFieldId = new ID("e0b7ceaa-3cbd-48f0-99f9-350c501eb3b9");
			public const string LinkFieldName = "Link";
			
		
			
			public static readonly ID NameFieldId = new ID("1fe8a8a2-87f2-49c2-80bb-108ef19ece16");
			public const string NameFieldName = "Name";
			
			

	}

	
	/// <summary>
	/// Social_Network
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Shared/Social Network</para>	
	/// <para>ID: e06a4f0b-6d79-423b-9c6f-5c54e6c62a9b</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISocial_NetworkConstants.TemplateIdString)] //, Cachable = true
	public partial class Social_Network  : GlassBase, ISocial_Network 
	{
	   
		
				/// <summary>
				/// The CSS Class field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 9ce4dc51-afa1-413d-a97f-70ec4c58c94f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISocial_NetworkConstants.CSS_ClassFieldName)]
				public virtual string CSS_Class  {get; set;}
					
		
				/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: e0b7ceaa-3cbd-48f0-99f9-350c501eb3b9</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISocial_NetworkConstants.LinkFieldName)]
				public virtual Link Link  {get; set;}
					
		
				/// <summary>
				/// The Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 1fe8a8a2-87f2-49c2-80bb-108ef19ece16</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISocial_NetworkConstants.NameFieldName)]
				public virtual string Name  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IWebsites Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Websites</para>	
	/// <para>ID: f91e4aaa-6de8-455f-b27a-e15a9230a758</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWebsitesConstants.TemplateIdString )] //, Cachable = true
	public partial interface IWebsites : IGlassBase 
	{
			
	}


	public static partial class IWebsitesConstants{

			public const string TemplateIdString = "f91e4aaa-6de8-455f-b27a-e15a9230a758";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Websites";

			

	}

	
	/// <summary>
	/// Websites
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Websites</para>	
	/// <para>ID: f91e4aaa-6de8-455f-b27a-e15a9230a758</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWebsitesConstants.TemplateIdString)] //, Cachable = true
	public partial class Websites  : GlassBase, IWebsites 
	{
	   
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IItem_Base Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Base/Item Base</para>	
	/// <para>ID: fa35d9ea-8c7b-423f-bda8-7cc6d759f4a8</para>	
	/// </summary>
	[SitecoreType(TemplateId=IItem_BaseConstants.TemplateIdString )] //, Cachable = true
	public partial interface IItem_Base : IGlassBase 
	{
			
					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: c6cda4a3-5d5b-445a-a33e-003bac3fe9d5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IItem_BaseConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: db7fef5a-0957-4fe3-abe6-e33bb46fc8c4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IItem_BaseConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IItem_BaseConstants{

			public const string TemplateIdString = "fa35d9ea-8c7b-423f-bda8-7cc6d759f4a8";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Item Base";

		
			
			public static readonly ID DescriptionFieldId = new ID("c6cda4a3-5d5b-445a-a33e-003bac3fe9d5");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("db7fef5a-0957-4fe3-abe6-e33bb46fc8c4");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Item_Base
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Base/Item Base</para>	
	/// <para>ID: fa35d9ea-8c7b-423f-bda8-7cc6d759f4a8</para>	
	/// </summary>
	[SitecoreType(TemplateId=IItem_BaseConstants.TemplateIdString)] //, Cachable = true
	public partial class Item_Base  : GlassBase, IItem_Base 
	{
	   
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c6cda4a3-5d5b-445a-a33e-003bac3fe9d5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IItem_BaseConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: db7fef5a-0957-4fe3-abe6-e33bb46fc8c4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IItem_BaseConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IHome Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Shared/Home</para>	
	/// <para>ID: fc678f71-56aa-47c7-9538-b8b968b93740</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHome : IGlassBase , global::MS.Sc.Models.IItem_Base, global::MS.Sc.Models.IMetadata
	{
			
	}


	public static partial class IHomeConstants{

			public const string TemplateIdString = "fc678f71-56aa-47c7-9538-b8b968b93740";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home";

		
			
			public static readonly ID DescriptionFieldId = new ID("c6cda4a3-5d5b-445a-a33e-003bac3fe9d5");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("db7fef5a-0957-4fe3-abe6-e33bb46fc8c4");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("b4ea1307-f39a-470f-84bb-ca7269fdb392");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("f1cd55be-14d3-4958-8e30-cc9789877818");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("ed6e4953-c3ef-4f60-b022-f6b024e54660");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Home
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Shared/Home</para>	
	/// <para>ID: fc678f71-56aa-47c7-9538-b8b968b93740</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString)] //, Cachable = true
	public partial class Home  : GlassBase, IHome 
	{
	   
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c6cda4a3-5d5b-445a-a33e-003bac3fe9d5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: db7fef5a-0957-4fe3-abe6-e33bb46fc8c4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b4ea1307-f39a-470f-84bb-ca7269fdb392</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f1cd55be-14d3-4958-8e30-cc9789877818</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ed6e4953-c3ef-4f60-b022-f6b024e54660</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
