






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace MS.Sc.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IPage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Base/Page</para>	
	/// <para>ID: 406cdf1f-63a9-40b1-839c-196695a966d1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPage : IGlassBase , global::MS.Sc.Models.IItem_Base, global::MS.Sc.Models.IMetadata
	{
			
					/// <summary>
					/// The CSS Classes field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: cdd223e1-4c95-47fb-a7a6-9670693cb243</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageConstants.CSS_ClassesFieldName)]
					string CSS_Classes  {get; set;}
			
			
					/// <summary>
					/// The Background Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: b24c74da-fccc-40c8-ae9e-d42fba7b4620</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageConstants.Background_ImageFieldName)]
					Image Background_Image  {get; set;}
			
			
	}


	public static partial class IPageConstants{

			public const string TemplateIdString = "406cdf1f-63a9-40b1-839c-196695a966d1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page";

		
			
			public static readonly ID CSS_ClassesFieldId = new ID("cdd223e1-4c95-47fb-a7a6-9670693cb243");
			public const string CSS_ClassesFieldName = "CSS Classes";
			
		
			
			public static readonly ID Background_ImageFieldId = new ID("b24c74da-fccc-40c8-ae9e-d42fba7b4620");
			public const string Background_ImageFieldName = "Background Image";
			
		
			
			public static readonly ID DescriptionFieldId = new ID("c6cda4a3-5d5b-445a-a33e-003bac3fe9d5");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("db7fef5a-0957-4fe3-abe6-e33bb46fc8c4");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("b4ea1307-f39a-470f-84bb-ca7269fdb392");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("f1cd55be-14d3-4958-8e30-cc9789877818");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("ed6e4953-c3ef-4f60-b022-f6b024e54660");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Base/Page</para>	
	/// <para>ID: 406cdf1f-63a9-40b1-839c-196695a966d1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageConstants.TemplateIdString)] //, Cachable = true
	public partial class Page  : GlassBase, IPage 
	{
	   
		
				/// <summary>
				/// The CSS Classes field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: cdd223e1-4c95-47fb-a7a6-9670693cb243</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.CSS_ClassesFieldName)]
				public virtual string CSS_Classes  {get; set;}
					
		
				/// <summary>
				/// The Background Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: b24c74da-fccc-40c8-ae9e-d42fba7b4620</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.Background_ImageFieldName)]
				public virtual Image Background_Image  {get; set;}
					
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c6cda4a3-5d5b-445a-a33e-003bac3fe9d5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: db7fef5a-0957-4fe3-abe6-e33bb46fc8c4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b4ea1307-f39a-470f-84bb-ca7269fdb392</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f1cd55be-14d3-4958-8e30-cc9789877818</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ed6e4953-c3ef-4f60-b022-f6b024e54660</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IHeader Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Shared/Header</para>	
	/// <para>ID: 4754ac46-0478-4958-b485-99329ae5f139</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHeaderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHeader : IGlassBase 
	{
			
					/// <summary>
					/// The Menu Items field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: bb1cbe07-0559-42b0-a44e-cd5bccb8ae65</para>
					/// <para>Custom Data: generic=Page</para>
					/// </summary>
					[SitecoreField(IHeaderConstants.Menu_ItemsFieldName)]
					IEnumerable<Page> Menu_Items  {get; set;}
			
			
					/// <summary>
					/// The Link Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 63be7af6-2aa4-46eb-be94-c8fb625a97c8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeaderConstants.Link_TitleFieldName)]
					string Link_Title  {get; set;}
			
			
					/// <summary>
					/// The Link field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: d82cc7f9-d223-4841-b73e-689422ab125d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeaderConstants.LinkFieldName)]
					Link Link  {get; set;}
			
			
					/// <summary>
					/// The Logo field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 88d1014d-febd-4a91-af80-204f7cf7e301</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeaderConstants.LogoFieldName)]
					Image Logo  {get; set;}
			
			
	}


	public static partial class IHeaderConstants{

			public const string TemplateIdString = "4754ac46-0478-4958-b485-99329ae5f139";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Header";

		
			
			public static readonly ID Menu_ItemsFieldId = new ID("bb1cbe07-0559-42b0-a44e-cd5bccb8ae65");
			public const string Menu_ItemsFieldName = "Menu Items";
			
		
			
			public static readonly ID Link_TitleFieldId = new ID("63be7af6-2aa4-46eb-be94-c8fb625a97c8");
			public const string Link_TitleFieldName = "Link Title";
			
		
			
			public static readonly ID LinkFieldId = new ID("d82cc7f9-d223-4841-b73e-689422ab125d");
			public const string LinkFieldName = "Link";
			
		
			
			public static readonly ID LogoFieldId = new ID("88d1014d-febd-4a91-af80-204f7cf7e301");
			public const string LogoFieldName = "Logo";
			
			

	}

	
	/// <summary>
	/// Header
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Shared/Header</para>	
	/// <para>ID: 4754ac46-0478-4958-b485-99329ae5f139</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHeaderConstants.TemplateIdString)] //, Cachable = true
	public partial class Header  : GlassBase, IHeader 
	{
	   
		
				/// <summary>
				/// The Menu Items field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: bb1cbe07-0559-42b0-a44e-cd5bccb8ae65</para>
				/// <para>Custom Data: generic=Page</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.Menu_ItemsFieldName)]
				public virtual IEnumerable<Page> Menu_Items  {get; set;}
					
		
				/// <summary>
				/// The Link Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 63be7af6-2aa4-46eb-be94-c8fb625a97c8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.Link_TitleFieldName)]
				public virtual string Link_Title  {get; set;}
					
		
				/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: d82cc7f9-d223-4841-b73e-689422ab125d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.LinkFieldName)]
				public virtual Link Link  {get; set;}
					
		
				/// <summary>
				/// The Logo field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 88d1014d-febd-4a91-af80-204f7cf7e301</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.LogoFieldName)]
				public virtual Image Logo  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// ISite Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Site</para>	
	/// <para>ID: 70e5cab5-fd8d-4073-be6b-cd2e1bf76fc7</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISite : IGlassBase 
	{
			
					/// <summary>
					/// The AnalyticsAccountCode field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: d226c608-b04c-4a78-b5ac-085a2194d0ed</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteConstants.AnalyticsAccountCodeFieldName)]
					string AnalyticsAccountCode  {get; set;}
			
			
	}


	public static partial class ISiteConstants{

			public const string TemplateIdString = "70e5cab5-fd8d-4073-be6b-cd2e1bf76fc7";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site";

		
			
			public static readonly ID AnalyticsAccountCodeFieldId = new ID("d226c608-b04c-4a78-b5ac-085a2194d0ed");
			public const string AnalyticsAccountCodeFieldName = "AnalyticsAccountCode";
			
			

	}

	
	/// <summary>
	/// Site
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Site</para>	
	/// <para>ID: 70e5cab5-fd8d-4073-be6b-cd2e1bf76fc7</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString)] //, Cachable = true
	public partial class Site  : GlassBase, ISite 
	{
	   
		
				/// <summary>
				/// The AnalyticsAccountCode field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d226c608-b04c-4a78-b5ac-085a2194d0ed</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteConstants.AnalyticsAccountCodeFieldName)]
				public virtual string AnalyticsAccountCode  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IMetadata Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Base/Metadata</para>	
	/// <para>ID: d476c1c3-20c1-4739-af76-2dec8c7c5c43</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMetadataConstants.TemplateIdString )] //, Cachable = true
	public partial interface IMetadata : IGlassBase 
	{
			
					/// <summary>
					/// The Meta Description field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b4ea1307-f39a-470f-84bb-ca7269fdb392</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMetadataConstants.Meta_DescriptionFieldName)]
					string Meta_Description  {get; set;}
			
			
					/// <summary>
					/// The Meta Keywords field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: f1cd55be-14d3-4958-8e30-cc9789877818</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMetadataConstants.Meta_KeywordsFieldName)]
					string Meta_Keywords  {get; set;}
			
			
					/// <summary>
					/// The Meta Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ed6e4953-c3ef-4f60-b022-f6b024e54660</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IMetadataConstants.Meta_TitleFieldName)]
					string Meta_Title  {get; set;}
			
			
	}


	public static partial class IMetadataConstants{

			public const string TemplateIdString = "d476c1c3-20c1-4739-af76-2dec8c7c5c43";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Metadata";

		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("b4ea1307-f39a-470f-84bb-ca7269fdb392");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("f1cd55be-14d3-4958-8e30-cc9789877818");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("ed6e4953-c3ef-4f60-b022-f6b024e54660");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Metadata
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Base/Metadata</para>	
	/// <para>ID: d476c1c3-20c1-4739-af76-2dec8c7c5c43</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMetadataConstants.TemplateIdString)] //, Cachable = true
	public partial class Metadata  : GlassBase, IMetadata 
	{
	   
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b4ea1307-f39a-470f-84bb-ca7269fdb392</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMetadataConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f1cd55be-14d3-4958-8e30-cc9789877818</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMetadataConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ed6e4953-c3ef-4f60-b022-f6b024e54660</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IMetadataConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IWebsites Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Websites</para>	
	/// <para>ID: f91e4aaa-6de8-455f-b27a-e15a9230a758</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWebsitesConstants.TemplateIdString )] //, Cachable = true
	public partial interface IWebsites : IGlassBase 
	{
			
	}


	public static partial class IWebsitesConstants{

			public const string TemplateIdString = "f91e4aaa-6de8-455f-b27a-e15a9230a758";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Websites";

			

	}

	
	/// <summary>
	/// Websites
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Global/Websites</para>	
	/// <para>ID: f91e4aaa-6de8-455f-b27a-e15a9230a758</para>	
	/// </summary>
	[SitecoreType(TemplateId=IWebsitesConstants.TemplateIdString)] //, Cachable = true
	public partial class Websites  : GlassBase, IWebsites 
	{
	   
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IItem_Base Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Base/Item Base</para>	
	/// <para>ID: fa35d9ea-8c7b-423f-bda8-7cc6d759f4a8</para>	
	/// </summary>
	[SitecoreType(TemplateId=IItem_BaseConstants.TemplateIdString )] //, Cachable = true
	public partial interface IItem_Base : IGlassBase 
	{
			
					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: c6cda4a3-5d5b-445a-a33e-003bac3fe9d5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IItem_BaseConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: db7fef5a-0957-4fe3-abe6-e33bb46fc8c4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IItem_BaseConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IItem_BaseConstants{

			public const string TemplateIdString = "fa35d9ea-8c7b-423f-bda8-7cc6d759f4a8";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Item Base";

		
			
			public static readonly ID DescriptionFieldId = new ID("c6cda4a3-5d5b-445a-a33e-003bac3fe9d5");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("db7fef5a-0957-4fe3-abe6-e33bb46fc8c4");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Item_Base
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Base/Item Base</para>	
	/// <para>ID: fa35d9ea-8c7b-423f-bda8-7cc6d759f4a8</para>	
	/// </summary>
	[SitecoreType(TemplateId=IItem_BaseConstants.TemplateIdString)] //, Cachable = true
	public partial class Item_Base  : GlassBase, IItem_Base 
	{
	   
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c6cda4a3-5d5b-445a-a33e-003bac3fe9d5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IItem_BaseConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: db7fef5a-0957-4fe3-abe6-e33bb46fc8c4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IItem_BaseConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace MS.Sc.Models
{


 	/// <summary>
	/// IHome Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Shared/Home</para>	
	/// <para>ID: fc678f71-56aa-47c7-9538-b8b968b93740</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHome : IGlassBase , global::MS.Sc.Models.IItem_Base, global::MS.Sc.Models.IMetadata
	{
			
	}


	public static partial class IHomeConstants{

			public const string TemplateIdString = "fc678f71-56aa-47c7-9538-b8b968b93740";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home";

		
			
			public static readonly ID DescriptionFieldId = new ID("c6cda4a3-5d5b-445a-a33e-003bac3fe9d5");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID TitleFieldId = new ID("db7fef5a-0957-4fe3-abe6-e33bb46fc8c4");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("b4ea1307-f39a-470f-84bb-ca7269fdb392");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("f1cd55be-14d3-4958-8e30-cc9789877818");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("ed6e4953-c3ef-4f60-b022-f6b024e54660");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Home
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Making Sense/Shared/Home</para>	
	/// <para>ID: fc678f71-56aa-47c7-9538-b8b968b93740</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString)] //, Cachable = true
	public partial class Home  : GlassBase, IHome 
	{
	   
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c6cda4a3-5d5b-445a-a33e-003bac3fe9d5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: db7fef5a-0957-4fe3-abe6-e33bb46fc8c4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b4ea1307-f39a-470f-84bb-ca7269fdb392</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: f1cd55be-14d3-4958-8e30-cc9789877818</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ed6e4953-c3ef-4f60-b022-f6b024e54660</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
